
enum Keyword {
    KW_NONE,
    KW_FN,
    KW_FOR,
    KW_NIL,
    KW_ENUM,
    KW_UNION,
    KW_STRUCT,
    KW_IF,
    KW_ELSE,
    KW_SWITCH,
    KW_CASE,
    KW_USING,
    KW_DEFER,
    KW_CAST,
    KW_AUTOCAST,
    KW_GOTO,
    KW_BREAK,
    KW_RETURN,
    KW_CONTINUE,
    KW_FALLTHROUGH,
    NUM_KEYWORDS,
};

const char *keywords[NUM_KEYWORDS] = {
    [KW_IF] = "if",
    [KW_FN] = "fn",
    [KW_FOR] = "for",
    [KW_NIL] = "nil",
    [KW_ENUM] = "enum",
    [KW_UNION] = "union",
    [KW_STRUCT] = "struct",
    [KW_ELSE] = "else",
    [KW_CASE] = "case",
    [KW_USING] = "using",
    [KW_DEFER] = "defer",
    [KW_CAST] = "cast",
    [KW_AUTOCAST] = "autocast",
    [KW_GOTO] = "goto",
    [KW_BREAK] = "break",
    [KW_RETURN] = "return",
    [KW_SWITCH] = "switch",
    [KW_CONTINUE] = "continue",
    [KW_FALLTHROUGH] = "fallthrough",
};
